# Generated by Django 6.0.6 on 2026-06-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('board_size', models.IntegerField()),
                ('obstacle_count', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Esperando'), ('RUNNING', 'En ejecución'), ('FINISHED', 'Finalizada')], default='WAITING', max_length=20)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lobby.room')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('obstacle_percentage', models.FloatField(default=30.0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('START', 'Inicio'), ('CAPTURE', 'Captura'), ('END', 'Fin')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('moves', models.IntegerField(default=0)),
                ('algorithm', models.CharField(choices=[('DIJKSTRA', 'Dijkstra'), ('FLOYD', 'Floyd-Warshall')], max_length=20)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('HUNTER', 'Hunter'), ('PREY', 'Prey')], max_length=20)),
                ('entity_number', models.IntegerField()),
                ('from_x', models.IntegerField()),
                ('from_y', models.IntegerField()),
                ('to_x', models.IntegerField()),
                ('to_y', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='game.board')),
            ],
        ),
        migrations.CreateModel(
            name='Prey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('alive', models.BooleanField(default=True)),
                ('moves', models.IntegerField(default=0)),
                ('survival_time', models.FloatField(default=0)),
                ('algorithm', models.CharField(choices=[('DIJKSTRA', 'Dijkstra'), ('FLOYD', 'Floyd-Warshall')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preys', to='game.game')),
            ],
        ),
    ]
