# Generated by Django 6.0.6 on 2026-06-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hunter_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movement',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prey',
            name='captured_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prey',
            name='ranking_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='game.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='lobby.room'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('START', 'Inicio'), ('CAPTURE', 'Captura'), ('END', 'Fin'), ('MAX_TURNS', 'Límite de turnos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunter', to='game.game'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='game.game'),
        ),
        migrations.AlterField(
            model_name='prey',
            name='survival_time',
            field=models.IntegerField(default=0),
        ),
    ]
