# Generated by Django 6.0.6 on 2026-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(blank=True, choices=[('HUNTER', 'Hunter'), ('PREY_1', 'Presa 1'), ('PREY_2', 'Presa 2'), ('PREY_3', 'Presa 3'), ('PREY_4', 'Presa 4')], max_length=20, null=True),
        ),
    ]
