# Generated by Django 6.0.6 on 2026-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_room_max_players_room_started_roomparticipant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('HUNTER', 'Cazador'), ('PREY_1', 'Presa 1'), ('PREY_2', 'Presa 2'), ('PREY_3', 'Presa 3'), ('PREY_4', 'Presa 4')], default='PREY_1', max_length=20),
        ),
    ]
